remote_theme: mmistakes/minimal-mistakes
title: "Hanbin Jang"

navigation:
  - title: "Home"
    url: /
  - title: "Academic History"
    url: /education/
  - title: "Research"
    url: /research/
  - title: "Projects"
    url: /projects/
